# fly.toml app configuration file generated for puddingbot on 2023-09-13T11:06:27-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "puddingbot"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="timeline_data"
  destination="/mnt/timeline_data"

[env]
  COMPUTERNAME = "FLY"